### ISSUE TITLE
exclude SSI includes

### ISSUE THREAD

**Issue by Sly777** [markhughes/HTMLMinify-Smarty#1]
Hey Mark, I'm trying to use this plugin on my app but the problem is I couldn't find exclude **SSI includes**. You can see the example below. How can I add this exclude for checks? I want to use them but Your minify plugin is cleaning all of them as well :)

For info: http://www.htmlgoodies.com/beyond/webmaster/article.php/3473341/SSI-The-Include-Command.htm

Example:
```
<div>
<h1>Hello World</h1>
<!--# include virtual="/who_i_am.html" -->
<!--# include virtual="/ajax_call_for_list.html" -->
</div>
```

Also I tried to add regex for this ```|<!\-{2}\#[\s\S]*?\-{2}>``` to **MINIFY_HTML_KEEP**. It doesn't work. And then I tried to continue on inside of the **fn_minify_html**. But also it doesn't work.

**Comment by markhughes** [comment]
I can see how this would be useful :) I'll work on it for you.

**Comment by markhughes** [comment]
7 years later.. I've implemented this.
